### ISSUE TITLE
Update noxorg.dev sample application to be compatible with latest nuget release for Nox.Lib

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox.Docs#14]
Closes https://github.com/NoxOrg/Nox.Docs/pull/16

**Comment by Mornevanzyl** [comment]
# Steps to include Nox and run appliction:

**Issue 1:**
Need to remove `"http": {}` profile from `launchSettings.json` to enable program to run on `https` protocol.

**Issue 2:**
Need to specify location of design files in `.csproj` file for generator to pick them up
```csharp
  <ItemGroup>
    <AdditionalFiles Include=".\.nox\design\**\*.yaml" />
  </ItemGroup>
```
This results in a success confirmation in `Generator.g.cs`:
```csharp
// Generated

#nullable enable

// Found files ->
//  - Currency.entity.nox.yaml
//  - SampleCurrency.solution.nox.yaml
// SUCCESS.
```
but an unsuccessful `dotnet build`
```powershell
C:\Users\Morne.VanZyl\Development\test7\SampleCurrencyService\Nox.Generator\Nox.Generator.NoxCodeGenerator\CurrenciesCo
ntroller.g.cs(11,29): error CS0234: The type or namespace name 'Application' does not exist in the namespace 'SampleCur
rencyService' (are you missing an assembly reference?) [C:\Users\Morne.VanZyl\Development\test7\SampleCurrencyService\S
ampleCurrencyService.csproj]
C:\Users\Morne.VanZyl\Development\test7\SampleCurrencyService\Nox.Generator\Nox.Generator.NoxCodeGenerator\CurrenciesCo
ntroller.g.cs(12,29): error CS0234: The type or namespace name 'Application' does not exist in the namespace 'SampleCur
rencyService' (are you missing an assembly reference?) [C:\Users\Morne.VanZyl\Development\test7\SampleCurrencyService\S
ampleCurrencyService.csproj]

Build FAILED.
```

To resolve this we have to specify the `Application:` node in the solution YAML file including at least one valid attribute:
```yaml
application:
  dataTransferObjects:
    - name: CountryDto
      description: Dto for country information
      attributes:
        - name: Id
          description: The identity of the country, the Iso Alpha 2 code
          type: text
          textTypeOptions:
            casing: lower
            maxLength: 2
            minLength: 2
```
This results in a clean build:
```powershell
C:\{pc.user.name}\Development\test7\SampleCurrencyService> dotnet build
MSBuild version 17.6.1+8ffc3fe3d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  SampleCurrencyService -> C:\Users\Morne.VanZyl\Development\test7\SampleCurrencyService\bin\Debug\net7.0\SampleCurrenc
  yService.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.00
```

**Issue 3:**
In `program.cs` we need to add an additional `using` statement to match the solution name. Otherwise the `builder.AddNox()` method isn't available:
```csharp
using Nox;
using SampleCurrencyService;
```
